Repository subspace/subspace-docs, pull requests merged in 2023-10, with the labels that each got.

#272 Version update for `gemini-3f-2023-oct-03`
  docs/protocol/pulsar.mdx
  docs/protocol/substrate-cli.mdx
  versioned_docs/version-latest/protocol/pulsar.mdx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: version

#276 Update Advanced CLI to `gemini-3f-2023-oct-06`
  docs/protocol/substrate-cli.mdx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: version

#277 Update Automated Notification Action
  .github/workflows/notification.yml
Labels: enhancement

#279 Update Pulsar to `v0.6.14-alpha`
  docs/protocol/pulsar.mdx
  versioned_docs/version-latest/protocol/pulsar.mdx
Labels: version

#281 Upgrade Docusaurus from `2.4.1` to `2.4.3` and Clarify DSN Documentation
  docs/protocol/substrate-cli.mdx
  package.json
  versioned_docs/version-latest/protocol/substrate-cli.mdx
  yarn.lock
Labels: enhancement

#284 Add FAQ to Common Problems Page
  docs/protocol/common_problems.md
  versioned_docs/version-latest/developers/faucet.md
  versioned_docs/version-latest/developers/general-information.md
  versioned_docs/version-latest/developers/intro.md
  versioned_docs/version-latest/developers/remix_guide.md
  versioned_docs/version-latest/protocol/common_problems.md
  versioned_docs/version-latest/protocol/pulsar.mdx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
  versioned_docs/version-latest/protocol/wallets/subwallet.md
Labels: enhancement

#199 Add staking and operators guide
  .gitignore
  docs/operators_and_staking/_category_.json
  docs/operators_and_staking/intro.md
  docs/operators_and_staking/operators.md
  docs/operators_and_staking/staking.md
  static/img/doc-imgs/operators-staking/Staking-1.png
  static/img/doc-imgs/operators-staking/Staking-10.png
  static/img/doc-imgs/operators-staking/Staking-11.png
  static/img/doc-imgs/operators-staking/Staking-12.png
  static/img/doc-imgs/operators-staking/Staking-13.png
  static/img/doc-imgs/operators-staking/Staking-14.png
  static/img/doc-imgs/operators-staking/Staking-15.png
  static/img/doc-imgs/operators-staking/Staking-16.png
  static/img/doc-imgs/operators-staking/Staking-17.png
  static/img/doc-imgs/operators-staking/Staking-18.png
  static/img/doc-imgs/operators-staking/Staking-19.png
  static/img/doc-imgs/operators-staking/Staking-2.png
  static/img/doc-imgs/operators-staking/Staking-20.png
  static/img/doc-imgs/operators-staking/Staking-21.png
  static/img/doc-imgs/operators-staking/Staking-22.png
  static/img/doc-imgs/operators-staking/Staking-23.png
  static/img/doc-imgs/operators-staking/Staking-24.png
  static/img/doc-imgs/operators-staking/Staking-25.png
  static/img/doc-imgs/operators-staking/Staking-26.png
  static/img/doc-imgs/operators-staking/Staking-27.png
  static/img/doc-imgs/operators-staking/Staking-3.png
  static/img/doc-imgs/operators-staking/Staking-4.png
  static/img/doc-imgs/operators-staking/Staking-5.png
  static/img/doc-imgs/operators-staking/Staking-6.png
  static/img/doc-imgs/operators-staking/Staking-7.png
  static/img/doc-imgs/operators-staking/Staking-8.png
  static/img/doc-imgs/operators-staking/Staking-9.png
  versioned_docs/version-latest/operators_and_staking/_category_.json
  versioned_docs/version-latest/operators_and_staking/intro.md
  versioned_docs/version-latest/operators_and_staking/operators.md
  versioned_docs/version-latest/operators_and_staking/staking.md
Labels: do not merge

#278 Introducing Automated Documentation Tag Updates
  .github/workflows/automated-release.yml
Labels: enhancement

#291 Added `🌏Help Translate` CTA
  docusaurus.config.js
Labels: enhancement

#295 Update state pruning command
  docs/protocol/substrate-cli.mdx
  src/components/SystemdServiceFileGenerator/index.jsx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: do not merge, gemini-3g

#305 Fix Typo on `--state-pruning archive-canonical`
  docs/protocol/substrate-cli.mdx
  src/components/SystemdServiceFileGenerator/index.jsx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: bug

#307 Update docs with new details for 3g
  docker-compose-auto.yml
  docs/protocol/substrate-cli.mdx
  src/components/DockerFileGenerator/index.jsx
  src/components/SystemdServiceFileGenerator/index.jsx
  versioned_docs/version-latest/operators_and_staking/_category_.json
  versioned_docs/version-latest/operators_and_staking/intro.md
  versioned_docs/version-latest/operators_and_staking/operators.md
  versioned_docs/version-latest/operators_and_staking/staking.md
  versioned_docs/version-latest/protocol/port-forwarding.md
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: version

#309 Fix missing `--no-private-ipv4` flag
  docs/protocol/substrate-cli.mdx
  src/components/DockerFileGenerator/index.jsx
  versioned_docs/version-latest/protocol/substrate-cli.mdx
Labels: bug
